const starfield=document.querySelector('.starfield');for(let i=0;i<110;i++){const el=document.createElement('span');el.className='star'+(i%9===0?' violet':'')+(i%17===0?' big':'');el.style.setProperty('--x',Math.random()*100+'%');el.style.setProperty('--y',Math.random()*100+'%');el.style.setProperty('--size',(Math.random()*2.4+.7)+'px');el.style.setProperty('--opacity',(Math.random()*.55+.25).toFixed(2));el.style.setProperty('--duration',(Math.random()*3+2.5).toFixed(2)+'s');el.style.setProperty('--delay',(-Math.random()*6).toFixed(2)+'s');el.style.setProperty('--drift',(Math.random()*18+8).toFixed(0)+'s');el.style.setProperty('--dx',(Math.random()*18-9).toFixed(1)+'px');el.style.setProperty('--dy',(Math.random()*18-9).toFixed(1)+'px');starfield.appendChild(el)}
const cards=[...document.querySelectorAll('.server-card')];let activeFilter='all';const search=document.getElementById('search');
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;filterServers()}));
search.addEventListener('input',filterServers);function filterServers(){const q=search.value.toLowerCase().trim();let shown=0;cards.forEach(c=>{const ok=c.dataset.name.toLowerCase().includes(q);const state=activeFilter==='all'||(activeFilter==='installed'&&c.dataset.state==='installed')||(activeFilter==='not'&&c.dataset.state==='not');c.style.display=ok&&state?'block':'none';if(ok&&state)shown++});document.getElementById('empty').style.display=shown?'none':'block'}
function openAdmin(name,initial,desc){document.getElementById('adminName').textContent=name;document.getElementById('adminName2').textContent=name;document.getElementById('adminDesc').textContent=desc;document.getElementById('adminAvatar').textContent=initial;document.getElementById('sideAvatar').textContent=initial;document.getElementById('sideName').textContent=name;document.getElementById('picker').classList.remove('active');document.getElementById('admin').classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function showPicker(){document.getElementById('admin').classList.remove('active');document.getElementById('picker').classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.display='none',2600)}
const advancedModules=['🔥 Rachas','💍 Matrimonios','🏢 Empresas','💰 AstraConomy','🛒 Tienda','❓ Daily Questions'];
const advancedNames=['Rachas','Matrimonios','Empresas','AstraConomy','Tienda','Daily Questions'];
// Estos módulos se mostrarán cuando Astra los tenga activados en el servidor. Por ahora no ocupan espacio en el panel.
document.querySelectorAll('.nav-item').forEach((b,i)=>{const label=b.textContent.trim();if(advancedNames.some(name=>label.includes(name))){b.remove()} });
document.querySelectorAll('.module').forEach(card=>{const title=card.querySelector('h3')?.textContent?.trim()||'';if(advancedNames.some(name=>title.includes(name)))card.remove()});
document.querySelectorAll('.nav-item').forEach((b,i)=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(i!==0)toast('Esta sección se conectará con Astra próximamente.') }));
