const MODULES={
'⚙️ General':['⚙️','Servidor','Configuración general','Idioma, zona horaria, canales y comportamiento de Astra.'],
'👋 Bienvenidas':['👋','Comunidad','Bienvenidas','Edita hasta 10 mensajes, con embed, imagen, canal, vista previa y prueba.'],
'🛡️ Moderación':['🛡️','Seguridad','Moderación','Filtros y acciones automáticas para mantener segura la comunidad.'],
'🤖 Autorrespuestas':['🤖','Automático','Autorrespuestas','Palabras clave y respuestas automáticas.'],
'📜 Logs':['📜','Registro','Logs','Selecciona eventos y el canal donde Astra debe registrarlos.'],
'🎭 Reacciones':['🎭','Social','Reacciones','Respuestas, GIFs y acciones automáticas.'],
'📊 Estadísticas':['📊','Datos','Estadísticas','Actividad y datos generales del servidor.'],
'⚙️ Permisos':['🔐','Acceso','Permisos','Roles que pueden utilizar y administrar Astra.']};
function controls(key){if(key==='👋 Bienvenidas')return `<div class="section-toolbar"><div><b>10 mensajes configurables</b><span>Cada mensaje puede activarse, editarse, previsualizarse y probarse.</span></div><button class="btn" onclick="toast('Nueva bienvenida creada (simulación)')">＋ Crear bienvenida</button></div><div class="welcome-list">${Array.from({length:10},(_,i)=>`<article class="config-card"><div class="config-icon">👋</div><div class="config-main"><div class="config-top"><div><h4>Bienvenida #${i+1}</h4><span class="status-pill ${i<2?'on':''}">${i<2?'● Activa':'○ Inactiva'}</span></div><label class="switch"><input type="checkbox" ${i<2?'checked':''}><i></i></label></div><p>${i<2?'¡Bienvenido {user} a {server}!':'Todavía no hay un mensaje configurado.'}</p><div class="config-actions"><button class="btn" onclick="editWelcome(${i+1})">Editar</button><button class="btn secondary" onclick="toast('Vista previa de Bienvenida #${i+1}')">Vista previa</button><button class="btn secondary" onclick="toast('Prueba enviada a #・bienvenidas')">Enviar prueba</button></div></div></article>`).join('')}</div>`;
if(key==='📜 Logs')return `<div class="log-channel"><div><b>Canal principal de logs</b><span>Usado si un evento no tiene canal específico.</span></div><select><option>#・logs</option><option>#・moderacion</option><option>#・servidor</option><option>Sin canal</option></select></div><div class="log-groups">${[['🛡','Moderación',['Bans','Kicks','Mutes','Warns']],['👥','Miembros',['Entradas','Salidas','Cambios de nickname']],['💬','Mensajes',['Mensajes eliminados','Mensajes editados']],['🎙','Voz',['Entradas y salidas']]].map(g=>`<div class="log-group"><div class="group-head"><div><b>${g[0]} ${g[1]}</b><span>Activa o desactiva este grupo.</span></div><label class="switch"><input type="checkbox" checked><i></i></label></div>${g[2].map(x=>`<div class="log-row"><span>${x}</span><select><option>#・logs</option><option>#・${g[1].toLowerCase()}</option><option>Sin canal</option></select></div>`).join('')}</div>`).join('')}</div>`;
return `<div class="settings-grid">${['Activar módulo','Respuestas automáticas','Canal principal','Acción predeterminada'].map((x,i)=>`<div class="setting-card"><div><b>${x}</b><span>Configuración visual de ${x.toLowerCase()}.</span></div>${i===2?'<select><option>#・general</option><option>#・chat</option><option>Sin canal</option></select>':i===3?'<button class="choice active">🗑️ Eliminar</button>':'<label class="switch"><input type="checkbox" '+(i===0?'checked':'')+'><i></i></label>'}</div>`).join('')}</div>`}
function renderAstraModule(btn){const key=btn.textContent.trim(),m=MODULES[key];if(!m)return;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));const c=document.querySelector('.admin-content'),name=document.getElementById('sideName')?.textContent||'Servidor',avatar=document.getElementById('sideAvatar')?.textContent||'A';c.innerHTML=`<div class="admin-head"><div class="admin-title"><div class="admin-avatar">${avatar}</div><div><h2>${name}</h2><p>Panel de administración de Astra</p></div></div><div class="admin-actions"><button class="btn secondary" onclick="showPicker()">← Volver</button><a class="btn secondary" href="../">Web de Astra</a></div></div><div class="notice">🔒 Estás administrando <b>${name}</b>. Las configuraciones pertenecen únicamente a este servidor.</div><div class="module-page"><div class="module-page-head"><div class="large-module-icon">${m[0]}</div><div><span class="module-tag">${m[1]}</span><h3>${m[2]}</h3><p>${m[3]}</p></div></div><div class="module-body">${controls(key)}</div><div class="save-bar"><span>Vista visual · todavía no modifica el bot.</span><button class="btn" onclick="toast('Cambios guardados (simulación)')">Guardar cambios</button></div></div>`;window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>renderAstraModule(b)));
function editWelcome(n){const o=document.createElement('div');o.className='modal-overlay';o.innerHTML=`<div class="modal"><button class="modal-close" onclick="this.closest('.modal-overlay').remove()">×</button><div class="modal-head"><div class="large-module-icon">👋</div><div><span class="module-tag">Bienvenida #${n}</span><h3>Editar mensaje</h3><p>Personaliza el embed y comprueba el resultado antes de guardarlo.</p></div></div><div class="editor-layout"><div class="editor-fields"><label>Título del embed<input value="¡Bienvenido a {server}!" /></label><label>Descripción<textarea>Nos alegra tenerte con nosotros, {user}. 🌙</textarea></label><div class="two-fields"><label>Color<input value="#A987FF" /></label><label>Canal<select><option>#・bienvenidas</option><option>#・general</option></select></label></div><label>Imagen del embed<input placeholder="URL de imagen (opcional)" /></label><div class="editor-actions"><button class="btn" onclick="toast('Bienvenida guardada (simulación)');this.closest('.modal-overlay').remove()">Guardar</button><button class="btn secondary" onclick="toast('Vista previa actualizada')">Vista previa</button></div></div><div class="discord-preview"><span>Vista previa</span><div class="preview-message"><small>ASTRABOT</small><h4>¡Bienvenido a {server}!</h4><p>Nos alegra tenerte con nosotros, {user}. 🌙</p><footer>Que disfrutes tu estadía ✦</footer></div></div></div></div>`;document.body.appendChild(o)}
